Server:
  RunMode: debug
  HttpPort: 8000
  ReadTimeout: 60
  WriteTimeout: 60
  Domain: 127.0.0.1

App:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogMaxSize: 100
  LogMaxAge: 30
  LogMaxBackups: 7
  LogSavePath: logs
  LogFileName: blog
  LogFileExt: .log
  LogLevel: debug
  TokenSecret: pl5u14Yyyr&WAxrvOpl5u14Y

Database:
  DBType: mysql
  Username: test_account
  Password: Test_account
  Host: rm-bp17ta209ggzi6t1mqo.mysql.rds.aliyuncs.com:3306
  DBName: blog_test
  TablePrefix: blog_
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
